# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debutform.ui'
#
# Created: Fri Apr 19 23:54:10 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DebutForm(object):
    def setupUi(self, DebutForm):
        DebutForm.setObjectName(_fromUtf8("DebutForm"))
        DebutForm.resize(661, 541)
        DebutForm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        DebutForm.setAcceptDrops(True)
        self.checkPromptQuit = QtGui.QCheckBox(DebutForm)
        self.checkPromptQuit.setGeometry(QtCore.QRect(150, 510, 111, 24))
        self.checkPromptQuit.setChecked(True)
        self.checkPromptQuit.setObjectName(_fromUtf8("checkPromptQuit"))
        self.buttonQuit = QtGui.QPushButton(DebutForm)
        self.buttonQuit.setGeometry(QtCore.QRect(550, 510, 101, 28))
        self.buttonQuit.setObjectName(_fromUtf8("buttonQuit"))
        self.groupSongData = QtGui.QGroupBox(DebutForm)
        self.groupSongData.setGeometry(QtCore.QRect(10, 300, 641, 201))
        self.groupSongData.setObjectName(_fromUtf8("groupSongData"))
        self.checkPromptChanges = QtGui.QCheckBox(self.groupSongData)
        self.checkPromptChanges.setGeometry(QtCore.QRect(10, 150, 135, 24))
        self.checkPromptChanges.setObjectName(_fromUtf8("checkPromptChanges"))
        self.label_6 = QtGui.QLabel(self.groupSongData)
        self.label_6.setGeometry(QtCore.QRect(30, 60, 54, 18))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupSongData)
        self.label_7.setGeometry(QtCore.QRect(490, 60, 44, 18))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.checkSongArtist = QtGui.QCheckBox(self.groupSongData)
        self.checkSongArtist.setGeometry(QtCore.QRect(10, 90, 53, 24))
        self.checkSongArtist.setObjectName(_fromUtf8("checkSongArtist"))
        self.textSongTrackNum = QtGui.QLineEdit(self.groupSongData)
        self.textSongTrackNum.setEnabled(True)
        self.textSongTrackNum.setGeometry(QtCore.QRect(550, 50, 41, 28))
        self.textSongTrackNum.setObjectName(_fromUtf8("textSongTrackNum"))
        self.textSongArtist = QtGui.QLineEdit(self.groupSongData)
        self.textSongArtist.setEnabled(False)
        self.textSongArtist.setGeometry(QtCore.QRect(140, 80, 481, 28))
        self.textSongArtist.setObjectName(_fromUtf8("textSongArtist"))
        self.textSongSong = QtGui.QLineEdit(self.groupSongData)
        self.textSongSong.setGeometry(QtCore.QRect(140, 50, 331, 28))
        self.textSongSong.setObjectName(_fromUtf8("textSongSong"))
        self.checkSongGenre = QtGui.QCheckBox(self.groupSongData)
        self.checkSongGenre.setGeometry(QtCore.QRect(10, 120, 57, 24))
        self.checkSongGenre.setObjectName(_fromUtf8("checkSongGenre"))
        self.textOutOfNumTracks = QtGui.QLabel(self.groupSongData)
        self.textOutOfNumTracks.setGeometry(QtCore.QRect(580, 60, 41, 20))
        self.textOutOfNumTracks.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textOutOfNumTracks.setWordWrap(False)
        self.textOutOfNumTracks.setObjectName(_fromUtf8("textOutOfNumTracks"))
        self.comboSongGenre = QtGui.QComboBox(self.groupSongData)
        self.comboSongGenre.setEnabled(False)
        self.comboSongGenre.setGeometry(QtCore.QRect(140, 110, 481, 28))
        self.comboSongGenre.setEditable(True)
        self.comboSongGenre.setObjectName(_fromUtf8("comboSongGenre"))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.comboSongGenre.addItem(_fromUtf8(""))
        self.textSongFilename = QtGui.QLineEdit(self.groupSongData)
        self.textSongFilename.setEnabled(False)
        self.textSongFilename.setGeometry(QtCore.QRect(140, 20, 481, 28))
        self.textSongFilename.setObjectName(_fromUtf8("textSongFilename"))
        self.label_10 = QtGui.QLabel(self.groupSongData)
        self.label_10.setGeometry(QtCore.QRect(30, 30, 111, 18))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.buttonSongReset = QtGui.QPushButton(self.groupSongData)
        self.buttonSongReset.setEnabled(False)
        self.buttonSongReset.setGeometry(QtCore.QRect(520, 140, 101, 28))
        self.buttonSongReset.setObjectName(_fromUtf8("buttonSongReset"))
        self.buttonSongNext = QtGui.QPushButton(self.groupSongData)
        self.buttonSongNext.setEnabled(False)
        self.buttonSongNext.setGeometry(QtCore.QRect(520, 170, 101, 28))
        self.buttonSongNext.setObjectName(_fromUtf8("buttonSongNext"))
        self.buttonSongPrev = QtGui.QPushButton(self.groupSongData)
        self.buttonSongPrev.setEnabled(False)
        self.buttonSongPrev.setGeometry(QtCore.QRect(410, 170, 101, 28))
        self.buttonSongPrev.setObjectName(_fromUtf8("buttonSongPrev"))
        self.groupAlbumData = QtGui.QGroupBox(DebutForm)
        self.groupAlbumData.setGeometry(QtCore.QRect(10, 0, 641, 301))
        self.groupAlbumData.setObjectName(_fromUtf8("groupAlbumData"))
        self.comboAlbumGenre = QtGui.QComboBox(self.groupAlbumData)
        self.comboAlbumGenre.setGeometry(QtCore.QRect(280, 110, 351, 28))
        self.comboAlbumGenre.setEditable(True)
        self.comboAlbumGenre.setObjectName(_fromUtf8("comboAlbumGenre"))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.comboAlbumGenre.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.groupAlbumData)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 30, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupAlbumData)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 61, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.groupAlbumData)
        self.label.setGeometry(QtCore.QRect(30, 120, 26, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupAlbumData)
        self.label_2.setGeometry(QtCore.QRect(230, 120, 34, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textAlbumArtist = QtGui.QLineEdit(self.groupAlbumData)
        self.textAlbumArtist.setGeometry(QtCore.QRect(120, 50, 401, 28))
        self.textAlbumArtist.setObjectName(_fromUtf8("textAlbumArtist"))
        self.textAlbumAlbum = QtGui.QLineEdit(self.groupAlbumData)
        self.textAlbumAlbum.setGeometry(QtCore.QRect(120, 80, 511, 28))
        self.textAlbumAlbum.setObjectName(_fromUtf8("textAlbumAlbum"))
        self.textAlbumDate = QtGui.QLineEdit(self.groupAlbumData)
        self.textAlbumDate.setGeometry(QtCore.QRect(120, 110, 71, 28))
        self.textAlbumDate.setText(_fromUtf8(""))
        self.textAlbumDate.setMaxLength(8)
        self.textAlbumDate.setObjectName(_fromUtf8("textAlbumDate"))
        self.label_5 = QtGui.QLabel(self.groupAlbumData)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 54, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textAlbumFolder = QtGui.QLineEdit(self.groupAlbumData)
        self.textAlbumFolder.setGeometry(QtCore.QRect(120, 20, 481, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textAlbumFolder.setPalette(palette)
        self.textAlbumFolder.setReadOnly(True)
        self.textAlbumFolder.setObjectName(_fromUtf8("textAlbumFolder"))
        self.checkVA = QtGui.QCheckBox(self.groupAlbumData)
        self.checkVA.setGeometry(QtCore.QRect(530, 50, 111, 24))
        self.checkVA.setObjectName(_fromUtf8("checkVA"))
        self.checkDeleteOtherTags = QtGui.QCheckBox(self.groupAlbumData)
        self.checkDeleteOtherTags.setGeometry(QtCore.QRect(10, 240, 151, 24))
        self.checkDeleteOtherTags.setChecked(True)
        self.checkDeleteOtherTags.setObjectName(_fromUtf8("checkDeleteOtherTags"))
        self.buttonAlbumDir = QtGui.QToolButton(self.groupAlbumData)
        self.buttonAlbumDir.setGeometry(QtCore.QRect(610, 20, 27, 24))
        self.buttonAlbumDir.setObjectName(_fromUtf8("buttonAlbumDir"))
        self.textAlbumComment = QtGui.QTextEdit(self.groupAlbumData)
        self.textAlbumComment.setGeometry(QtCore.QRect(120, 140, 511, 56))
        self.textAlbumComment.setObjectName(_fromUtf8("textAlbumComment"))
        self.label_8 = QtGui.QLabel(self.groupAlbumData)
        self.label_8.setGeometry(QtCore.QRect(30, 150, 55, 18))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.textGroup = QtGui.QLineEdit(self.groupAlbumData)
        self.textGroup.setGeometry(QtCore.QRect(120, 200, 331, 28))
        self.textGroup.setObjectName(_fromUtf8("textGroup"))
        self.label_9 = QtGui.QLabel(self.groupAlbumData)
        self.label_9.setGeometry(QtCore.QRect(30, 210, 41, 18))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.checkAlbumGroupAppend = QtGui.QCheckBox(self.groupAlbumData)
        self.checkAlbumGroupAppend.setGeometry(QtCore.QRect(460, 200, 151, 24))
        self.checkAlbumGroupAppend.setChecked(True)
        self.checkAlbumGroupAppend.setObjectName(_fromUtf8("checkAlbumGroupAppend"))
        self.buttonAlbumReset = QtGui.QPushButton(self.groupAlbumData)
        self.buttonAlbumReset.setEnabled(False)
        self.buttonAlbumReset.setGeometry(QtCore.QRect(530, 270, 101, 28))
        self.buttonAlbumReset.setObjectName(_fromUtf8("buttonAlbumReset"))
        self.buttonAlbumApply = QtGui.QPushButton(self.groupAlbumData)
        self.buttonAlbumApply.setEnabled(False)
        self.buttonAlbumApply.setGeometry(QtCore.QRect(420, 270, 101, 28))
        self.buttonAlbumApply.setObjectName(_fromUtf8("buttonAlbumApply"))
        self.checkAlbumTranslit = QtGui.QCheckBox(self.groupAlbumData)
        self.checkAlbumTranslit.setGeometry(QtCore.QRect(150, 240, 144, 24))
        self.checkAlbumTranslit.setObjectName(_fromUtf8("checkAlbumTranslit"))
        self.comboAlbumTranslit = QtGui.QComboBox(self.groupAlbumData)
        self.comboAlbumTranslit.setEnabled(False)
        self.comboAlbumTranslit.setGeometry(QtCore.QRect(300, 240, 151, 28))
        self.comboAlbumTranslit.setObjectName(_fromUtf8("comboAlbumTranslit"))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.comboAlbumTranslit.addItem(_fromUtf8(""))
        self.buttonPrefs = QtGui.QPushButton(DebutForm)
        self.buttonPrefs.setGeometry(QtCore.QRect(440, 510, 101, 28))
        self.buttonPrefs.setObjectName(_fromUtf8("buttonPrefs"))
        self.checkPromptReset = QtGui.QCheckBox(DebutForm)
        self.checkPromptReset.setGeometry(QtCore.QRect(10, 510, 131, 24))
        self.checkPromptReset.setChecked(True)
        self.checkPromptReset.setObjectName(_fromUtf8("checkPromptReset"))

        self.retranslateUi(DebutForm)
        QtCore.QObject.connect(self.checkVA, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.textAlbumArtist.setDisabled)
        QtCore.QObject.connect(self.checkVA, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkSongArtist.setChecked)
        QtCore.QObject.connect(self.checkSongArtist, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.textSongArtist.setEnabled)
        QtCore.QObject.connect(self.checkSongGenre, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboAlbumGenre.setDisabled)
        QtCore.QObject.connect(self.checkSongGenre, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboSongGenre.setEnabled)
        QtCore.QObject.connect(self.checkSongArtist, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.textAlbumArtist.setDisabled)
        QtCore.QObject.connect(self.checkAlbumTranslit, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboAlbumTranslit.setEnabled)
        QtCore.QObject.connect(self.textAlbumArtist, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.textSongArtist.setText)
        QtCore.QObject.connect(self.checkSongArtist, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkVA.setChecked)
        QtCore.QMetaObject.connectSlotsByName(DebutForm)
        DebutForm.setTabOrder(self.textAlbumFolder, self.buttonAlbumDir)
        DebutForm.setTabOrder(self.buttonAlbumDir, self.textAlbumArtist)
        DebutForm.setTabOrder(self.textAlbumArtist, self.checkVA)
        DebutForm.setTabOrder(self.checkVA, self.textAlbumAlbum)
        DebutForm.setTabOrder(self.textAlbumAlbum, self.textAlbumDate)
        DebutForm.setTabOrder(self.textAlbumDate, self.comboAlbumGenre)
        DebutForm.setTabOrder(self.comboAlbumGenre, self.textAlbumComment)
        DebutForm.setTabOrder(self.textAlbumComment, self.textGroup)
        DebutForm.setTabOrder(self.textGroup, self.checkAlbumGroupAppend)
        DebutForm.setTabOrder(self.checkAlbumGroupAppend, self.checkDeleteOtherTags)
        DebutForm.setTabOrder(self.checkDeleteOtherTags, self.checkAlbumTranslit)
        DebutForm.setTabOrder(self.checkAlbumTranslit, self.comboAlbumTranslit)
        DebutForm.setTabOrder(self.comboAlbumTranslit, self.buttonAlbumApply)
        DebutForm.setTabOrder(self.buttonAlbumApply, self.buttonAlbumReset)
        DebutForm.setTabOrder(self.buttonAlbumReset, self.textSongFilename)
        DebutForm.setTabOrder(self.textSongFilename, self.textSongSong)
        DebutForm.setTabOrder(self.textSongSong, self.textSongTrackNum)
        DebutForm.setTabOrder(self.textSongTrackNum, self.checkSongArtist)
        DebutForm.setTabOrder(self.checkSongArtist, self.textSongArtist)
        DebutForm.setTabOrder(self.textSongArtist, self.checkSongGenre)
        DebutForm.setTabOrder(self.checkSongGenre, self.comboSongGenre)
        DebutForm.setTabOrder(self.comboSongGenre, self.checkPromptChanges)
        DebutForm.setTabOrder(self.checkPromptChanges, self.buttonSongReset)
        DebutForm.setTabOrder(self.buttonSongReset, self.buttonSongPrev)
        DebutForm.setTabOrder(self.buttonSongPrev, self.buttonSongNext)
        DebutForm.setTabOrder(self.buttonSongNext, self.checkPromptReset)
        DebutForm.setTabOrder(self.checkPromptReset, self.checkPromptQuit)
        DebutForm.setTabOrder(self.checkPromptQuit, self.buttonPrefs)
        DebutForm.setTabOrder(self.buttonPrefs, self.buttonQuit)

    def retranslateUi(self, DebutForm):
        DebutForm.setWindowTitle(_translate("DebutForm", "Debut", None))
        self.checkPromptQuit.setText(_translate("DebutForm", "Pro&mpt on quit", None))
        self.buttonQuit.setText(_translate("DebutForm", "&Quit", None))
        self.groupSongData.setTitle(_translate("DebutForm", "Song data", None))
        self.checkPromptChanges.setText(_translate("DebutForm", "Pr&ompt for changes", None))
        self.label_6.setText(_translate("DebutForm", "Song title", None))
        self.label_7.setText(_translate("DebutForm", "Track #", None))
        self.checkSongArtist.setText(_translate("DebutForm", "&Artist", None))
        self.checkSongGenre.setText(_translate("DebutForm", "&Genre", None))
        self.textOutOfNumTracks.setText(_translate("DebutForm", "/ 0", None))
        self.comboSongGenre.setItemText(0, _translate("DebutForm", "A Capella", None))
        self.comboSongGenre.setItemText(1, _translate("DebutForm", "Acid", None))
        self.comboSongGenre.setItemText(2, _translate("DebutForm", "Acid Jazz", None))
        self.comboSongGenre.setItemText(3, _translate("DebutForm", "Acid Punk", None))
        self.comboSongGenre.setItemText(4, _translate("DebutForm", "Acoustic", None))
        self.comboSongGenre.setItemText(5, _translate("DebutForm", "Alternative", None))
        self.comboSongGenre.setItemText(6, _translate("DebutForm", "Alternative Rock", None))
        self.comboSongGenre.setItemText(7, _translate("DebutForm", "Ambient", None))
        self.comboSongGenre.setItemText(8, _translate("DebutForm", "Avantgarde", None))
        self.comboSongGenre.setItemText(9, _translate("DebutForm", "Ballad", None))
        self.comboSongGenre.setItemText(10, _translate("DebutForm", "Bass", None))
        self.comboSongGenre.setItemText(11, _translate("DebutForm", "Bebop", None))
        self.comboSongGenre.setItemText(12, _translate("DebutForm", "Big Band", None))
        self.comboSongGenre.setItemText(13, _translate("DebutForm", "Bluegrass", None))
        self.comboSongGenre.setItemText(14, _translate("DebutForm", "Blues", None))
        self.comboSongGenre.setItemText(15, _translate("DebutForm", "Booty Bass", None))
        self.comboSongGenre.setItemText(16, _translate("DebutForm", "Cabaret", None))
        self.comboSongGenre.setItemText(17, _translate("DebutForm", "Celtic", None))
        self.comboSongGenre.setItemText(18, _translate("DebutForm", "Chamber Music", None))
        self.comboSongGenre.setItemText(19, _translate("DebutForm", "Chanson", None))
        self.comboSongGenre.setItemText(20, _translate("DebutForm", "Chorus", None))
        self.comboSongGenre.setItemText(21, _translate("DebutForm", "Christian Rap", None))
        self.comboSongGenre.setItemText(22, _translate("DebutForm", "Classic Rock", None))
        self.comboSongGenre.setItemText(23, _translate("DebutForm", "Classical", None))
        self.comboSongGenre.setItemText(24, _translate("DebutForm", "Club", None))
        self.comboSongGenre.setItemText(25, _translate("DebutForm", "Comedy", None))
        self.comboSongGenre.setItemText(26, _translate("DebutForm", "Country", None))
        self.comboSongGenre.setItemText(27, _translate("DebutForm", "Cult", None))
        self.comboSongGenre.setItemText(28, _translate("DebutForm", "Dance", None))
        self.comboSongGenre.setItemText(29, _translate("DebutForm", "Dance Hall", None))
        self.comboSongGenre.setItemText(30, _translate("DebutForm", "Darkwave", None))
        self.comboSongGenre.setItemText(31, _translate("DebutForm", "Death Metal", None))
        self.comboSongGenre.setItemText(32, _translate("DebutForm", "Disco", None))
        self.comboSongGenre.setItemText(33, _translate("DebutForm", "Dream", None))
        self.comboSongGenre.setItemText(34, _translate("DebutForm", "Drum & Bass", None))
        self.comboSongGenre.setItemText(35, _translate("DebutForm", "Drum Solo", None))
        self.comboSongGenre.setItemText(36, _translate("DebutForm", "Duet", None))
        self.comboSongGenre.setItemText(37, _translate("DebutForm", "Easy Listening", None))
        self.comboSongGenre.setItemText(38, _translate("DebutForm", "Electronic", None))
        self.comboSongGenre.setItemText(39, _translate("DebutForm", "Ethnic", None))
        self.comboSongGenre.setItemText(40, _translate("DebutForm", "Euro-House", None))
        self.comboSongGenre.setItemText(41, _translate("DebutForm", "Euro-Techno", None))
        self.comboSongGenre.setItemText(42, _translate("DebutForm", "Eurobeat", None))
        self.comboSongGenre.setItemText(43, _translate("DebutForm", "Eurodance", None))
        self.comboSongGenre.setItemText(44, _translate("DebutForm", "Fast Fusion", None))
        self.comboSongGenre.setItemText(45, _translate("DebutForm", "Freeform", None))
        self.comboSongGenre.setItemText(46, _translate("DebutForm", "Freestyle", None))
        self.comboSongGenre.setItemText(47, _translate("DebutForm", "Folk", None))
        self.comboSongGenre.setItemText(48, _translate("DebutForm", "Folk-Rock", None))
        self.comboSongGenre.setItemText(49, _translate("DebutForm", "Folklore", None))
        self.comboSongGenre.setItemText(50, _translate("DebutForm", "Funk", None))
        self.comboSongGenre.setItemText(51, _translate("DebutForm", "Gabber", None))
        self.comboSongGenre.setItemText(52, _translate("DebutForm", "Game", None))
        self.comboSongGenre.setItemText(53, _translate("DebutForm", "Gangsta", None))
        self.comboSongGenre.setItemText(54, _translate("DebutForm", "Goa", None))
        self.comboSongGenre.setItemText(55, _translate("DebutForm", "Gospel", None))
        self.comboSongGenre.setItemText(56, _translate("DebutForm", "Gothic", None))
        self.comboSongGenre.setItemText(57, _translate("DebutForm", "Gothic Rock", None))
        self.comboSongGenre.setItemText(58, _translate("DebutForm", "Grunge", None))
        self.comboSongGenre.setItemText(59, _translate("DebutForm", "Happy Hardcore", None))
        self.comboSongGenre.setItemText(60, _translate("DebutForm", "Hardcore", None))
        self.comboSongGenre.setItemText(61, _translate("DebutForm", "Hip-Hop", None))
        self.comboSongGenre.setItemText(62, _translate("DebutForm", "House", None))
        self.comboSongGenre.setItemText(63, _translate("DebutForm", "Humour", None))
        self.comboSongGenre.setItemText(64, _translate("DebutForm", "Industrial", None))
        self.comboSongGenre.setItemText(65, _translate("DebutForm", "Instrumental", None))
        self.comboSongGenre.setItemText(66, _translate("DebutForm", "Instrumental Pop", None))
        self.comboSongGenre.setItemText(67, _translate("DebutForm", "Instrumental Rock", None))
        self.comboSongGenre.setItemText(68, _translate("DebutForm", "Jazz", None))
        self.comboSongGenre.setItemText(69, _translate("DebutForm", "J-Pop", None))
        self.comboSongGenre.setItemText(70, _translate("DebutForm", "Jungle", None))
        self.comboSongGenre.setItemText(71, _translate("DebutForm", "Latin", None))
        self.comboSongGenre.setItemText(72, _translate("DebutForm", "Lo-Fi", None))
        self.comboSongGenre.setItemText(73, _translate("DebutForm", "Meditative", None))
        self.comboSongGenre.setItemText(74, _translate("DebutForm", "Metal", None))
        self.comboSongGenre.setItemText(75, _translate("DebutForm", "Musical", None))
        self.comboSongGenre.setItemText(76, _translate("DebutForm", "National Folk", None))
        self.comboSongGenre.setItemText(77, _translate("DebutForm", "Native US", None))
        self.comboSongGenre.setItemText(78, _translate("DebutForm", "New Age", None))
        self.comboSongGenre.setItemText(79, _translate("DebutForm", "New Wave", None))
        self.comboSongGenre.setItemText(80, _translate("DebutForm", "Noise", None))
        self.comboSongGenre.setItemText(81, _translate("DebutForm", "Oldies", None))
        self.comboSongGenre.setItemText(82, _translate("DebutForm", "Opera", None))
        self.comboSongGenre.setItemText(83, _translate("DebutForm", "Other", None))
        self.comboSongGenre.setItemText(84, _translate("DebutForm", "Polka", None))
        self.comboSongGenre.setItemText(85, _translate("DebutForm", "Pop", None))
        self.comboSongGenre.setItemText(86, _translate("DebutForm", "Pop-Folk", None))
        self.comboSongGenre.setItemText(87, _translate("DebutForm", "Pop/Funk", None))
        self.comboSongGenre.setItemText(88, _translate("DebutForm", "Porn Groove", None))
        self.comboSongGenre.setItemText(89, _translate("DebutForm", "Power Ballad", None))
        self.comboSongGenre.setItemText(90, _translate("DebutForm", "Pranks", None))
        self.comboSongGenre.setItemText(91, _translate("DebutForm", "Primus", None))
        self.comboSongGenre.setItemText(92, _translate("DebutForm", "Progressive Rock", None))
        self.comboSongGenre.setItemText(93, _translate("DebutForm", "Psychadelic", None))
        self.comboSongGenre.setItemText(94, _translate("DebutForm", "Psychadelic Rock", None))
        self.comboSongGenre.setItemText(95, _translate("DebutForm", "Punk", None))
        self.comboSongGenre.setItemText(96, _translate("DebutForm", "Punk Rock", None))
        self.comboSongGenre.setItemText(97, _translate("DebutForm", "R&B", None))
        self.comboSongGenre.setItemText(98, _translate("DebutForm", "Rap", None))
        self.comboSongGenre.setItemText(99, _translate("DebutForm", "Rave", None))
        self.comboSongGenre.setItemText(100, _translate("DebutForm", "Reggae", None))
        self.comboSongGenre.setItemText(101, _translate("DebutForm", "Retro", None))
        self.comboSongGenre.setItemText(102, _translate("DebutForm", "Revival", None))
        self.comboSongGenre.setItemText(103, _translate("DebutForm", "Rhythmic Soul", None))
        self.comboSongGenre.setItemText(104, _translate("DebutForm", "Rock", None))
        self.comboSongGenre.setItemText(105, _translate("DebutForm", "Rock & Roll", None))
        self.comboSongGenre.setItemText(106, _translate("DebutForm", "Samba", None))
        self.comboSongGenre.setItemText(107, _translate("DebutForm", "Satire", None))
        self.comboSongGenre.setItemText(108, _translate("DebutForm", "Showtunes", None))
        self.comboSongGenre.setItemText(109, _translate("DebutForm", "Ska", None))
        self.comboSongGenre.setItemText(110, _translate("DebutForm", "Slow Jam", None))
        self.comboSongGenre.setItemText(111, _translate("DebutForm", "Slow Rock", None))
        self.comboSongGenre.setItemText(112, _translate("DebutForm", "Sonata", None))
        self.comboSongGenre.setItemText(113, _translate("DebutForm", "Soul", None))
        self.comboSongGenre.setItemText(114, _translate("DebutForm", "Sound Clip", None))
        self.comboSongGenre.setItemText(115, _translate("DebutForm", "Soundtrack", None))
        self.comboSongGenre.setItemText(116, _translate("DebutForm", "Southern Rock", None))
        self.comboSongGenre.setItemText(117, _translate("DebutForm", "Space", None))
        self.comboSongGenre.setItemText(118, _translate("DebutForm", "Speech", None))
        self.comboSongGenre.setItemText(119, _translate("DebutForm", "Swing", None))
        self.comboSongGenre.setItemText(120, _translate("DebutForm", "Symphonic Rock", None))
        self.comboSongGenre.setItemText(121, _translate("DebutForm", "Symphony", None))
        self.comboSongGenre.setItemText(122, _translate("DebutForm", "Tango", None))
        self.comboSongGenre.setItemText(123, _translate("DebutForm", "Techno", None))
        self.comboSongGenre.setItemText(124, _translate("DebutForm", "Techno-Industrial", None))
        self.comboSongGenre.setItemText(125, _translate("DebutForm", "Terror", None))
        self.comboSongGenre.setItemText(126, _translate("DebutForm", "Top 40", None))
        self.comboSongGenre.setItemText(127, _translate("DebutForm", "Trailer", None))
        self.comboSongGenre.setItemText(128, _translate("DebutForm", "Trance", None))
        self.comboSongGenre.setItemText(129, _translate("DebutForm", "Trancecore", None))
        self.comboSongGenre.setItemText(130, _translate("DebutForm", "Tribal", None))
        self.comboSongGenre.setItemText(131, _translate("DebutForm", "Trip-Hop", None))
        self.comboSongGenre.setItemText(132, _translate("DebutForm", "Varies", None))
        self.comboSongGenre.setItemText(133, _translate("DebutForm", "Vocal", None))
        self.comboSongGenre.setItemText(134, _translate("DebutForm", "World Music", None))
        self.label_10.setText(_translate("DebutForm", "Preview file name", None))
        self.buttonSongReset.setText(_translate("DebutForm", "R&eset", None))
        self.buttonSongNext.setText(_translate("DebutForm", "&Next >", None))
        self.buttonSongPrev.setText(_translate("DebutForm", "< &Previous", None))
        self.groupAlbumData.setTitle(_translate("DebutForm", "Album data", None))
        self.comboAlbumGenre.setItemText(0, _translate("DebutForm", "A Capella", None))
        self.comboAlbumGenre.setItemText(1, _translate("DebutForm", "Acid", None))
        self.comboAlbumGenre.setItemText(2, _translate("DebutForm", "Acid Jazz", None))
        self.comboAlbumGenre.setItemText(3, _translate("DebutForm", "Acid Punk", None))
        self.comboAlbumGenre.setItemText(4, _translate("DebutForm", "Acoustic", None))
        self.comboAlbumGenre.setItemText(5, _translate("DebutForm", "Alternative", None))
        self.comboAlbumGenre.setItemText(6, _translate("DebutForm", "Alternative Rock", None))
        self.comboAlbumGenre.setItemText(7, _translate("DebutForm", "Ambient", None))
        self.comboAlbumGenre.setItemText(8, _translate("DebutForm", "Avantgarde", None))
        self.comboAlbumGenre.setItemText(9, _translate("DebutForm", "Ballad", None))
        self.comboAlbumGenre.setItemText(10, _translate("DebutForm", "Bass", None))
        self.comboAlbumGenre.setItemText(11, _translate("DebutForm", "Bebop", None))
        self.comboAlbumGenre.setItemText(12, _translate("DebutForm", "Big Band", None))
        self.comboAlbumGenre.setItemText(13, _translate("DebutForm", "Bluegrass", None))
        self.comboAlbumGenre.setItemText(14, _translate("DebutForm", "Blues", None))
        self.comboAlbumGenre.setItemText(15, _translate("DebutForm", "Booty Bass", None))
        self.comboAlbumGenre.setItemText(16, _translate("DebutForm", "Cabaret", None))
        self.comboAlbumGenre.setItemText(17, _translate("DebutForm", "Celtic", None))
        self.comboAlbumGenre.setItemText(18, _translate("DebutForm", "Chamber Music", None))
        self.comboAlbumGenre.setItemText(19, _translate("DebutForm", "Chanson", None))
        self.comboAlbumGenre.setItemText(20, _translate("DebutForm", "Chorus", None))
        self.comboAlbumGenre.setItemText(21, _translate("DebutForm", "Christian Rap", None))
        self.comboAlbumGenre.setItemText(22, _translate("DebutForm", "Classic Rock", None))
        self.comboAlbumGenre.setItemText(23, _translate("DebutForm", "Classical", None))
        self.comboAlbumGenre.setItemText(24, _translate("DebutForm", "Club", None))
        self.comboAlbumGenre.setItemText(25, _translate("DebutForm", "Comedy", None))
        self.comboAlbumGenre.setItemText(26, _translate("DebutForm", "Country", None))
        self.comboAlbumGenre.setItemText(27, _translate("DebutForm", "Cult", None))
        self.comboAlbumGenre.setItemText(28, _translate("DebutForm", "Dance", None))
        self.comboAlbumGenre.setItemText(29, _translate("DebutForm", "Dance Hall", None))
        self.comboAlbumGenre.setItemText(30, _translate("DebutForm", "Darkwave", None))
        self.comboAlbumGenre.setItemText(31, _translate("DebutForm", "Death Metal", None))
        self.comboAlbumGenre.setItemText(32, _translate("DebutForm", "Disco", None))
        self.comboAlbumGenre.setItemText(33, _translate("DebutForm", "Dream", None))
        self.comboAlbumGenre.setItemText(34, _translate("DebutForm", "Drum & Bass", None))
        self.comboAlbumGenre.setItemText(35, _translate("DebutForm", "Drum Solo", None))
        self.comboAlbumGenre.setItemText(36, _translate("DebutForm", "Duet", None))
        self.comboAlbumGenre.setItemText(37, _translate("DebutForm", "Easy Listening", None))
        self.comboAlbumGenre.setItemText(38, _translate("DebutForm", "Electronic", None))
        self.comboAlbumGenre.setItemText(39, _translate("DebutForm", "Ethnic", None))
        self.comboAlbumGenre.setItemText(40, _translate("DebutForm", "Euro-House", None))
        self.comboAlbumGenre.setItemText(41, _translate("DebutForm", "Euro-Techno", None))
        self.comboAlbumGenre.setItemText(42, _translate("DebutForm", "Eurobeat", None))
        self.comboAlbumGenre.setItemText(43, _translate("DebutForm", "Eurodance", None))
        self.comboAlbumGenre.setItemText(44, _translate("DebutForm", "Fast Fusion", None))
        self.comboAlbumGenre.setItemText(45, _translate("DebutForm", "Freeform", None))
        self.comboAlbumGenre.setItemText(46, _translate("DebutForm", "Freestyle", None))
        self.comboAlbumGenre.setItemText(47, _translate("DebutForm", "Folk", None))
        self.comboAlbumGenre.setItemText(48, _translate("DebutForm", "Folk-Rock", None))
        self.comboAlbumGenre.setItemText(49, _translate("DebutForm", "Folklore", None))
        self.comboAlbumGenre.setItemText(50, _translate("DebutForm", "Funk", None))
        self.comboAlbumGenre.setItemText(51, _translate("DebutForm", "Gabber", None))
        self.comboAlbumGenre.setItemText(52, _translate("DebutForm", "Game", None))
        self.comboAlbumGenre.setItemText(53, _translate("DebutForm", "Gangsta", None))
        self.comboAlbumGenre.setItemText(54, _translate("DebutForm", "Goa", None))
        self.comboAlbumGenre.setItemText(55, _translate("DebutForm", "Gospel", None))
        self.comboAlbumGenre.setItemText(56, _translate("DebutForm", "Gothic", None))
        self.comboAlbumGenre.setItemText(57, _translate("DebutForm", "Gothic Rock", None))
        self.comboAlbumGenre.setItemText(58, _translate("DebutForm", "Grunge", None))
        self.comboAlbumGenre.setItemText(59, _translate("DebutForm", "Happy Hardcore", None))
        self.comboAlbumGenre.setItemText(60, _translate("DebutForm", "Hardcore", None))
        self.comboAlbumGenre.setItemText(61, _translate("DebutForm", "Hip-Hop", None))
        self.comboAlbumGenre.setItemText(62, _translate("DebutForm", "House", None))
        self.comboAlbumGenre.setItemText(63, _translate("DebutForm", "Humour", None))
        self.comboAlbumGenre.setItemText(64, _translate("DebutForm", "Industrial", None))
        self.comboAlbumGenre.setItemText(65, _translate("DebutForm", "Instrumental", None))
        self.comboAlbumGenre.setItemText(66, _translate("DebutForm", "Instrumental Pop", None))
        self.comboAlbumGenre.setItemText(67, _translate("DebutForm", "Instrumental Rock", None))
        self.comboAlbumGenre.setItemText(68, _translate("DebutForm", "Jazz", None))
        self.comboAlbumGenre.setItemText(69, _translate("DebutForm", "J-Pop", None))
        self.comboAlbumGenre.setItemText(70, _translate("DebutForm", "Jungle", None))
        self.comboAlbumGenre.setItemText(71, _translate("DebutForm", "Latin", None))
        self.comboAlbumGenre.setItemText(72, _translate("DebutForm", "Lo-Fi", None))
        self.comboAlbumGenre.setItemText(73, _translate("DebutForm", "Meditative", None))
        self.comboAlbumGenre.setItemText(74, _translate("DebutForm", "Metal", None))
        self.comboAlbumGenre.setItemText(75, _translate("DebutForm", "Musical", None))
        self.comboAlbumGenre.setItemText(76, _translate("DebutForm", "National Folk", None))
        self.comboAlbumGenre.setItemText(77, _translate("DebutForm", "Native US", None))
        self.comboAlbumGenre.setItemText(78, _translate("DebutForm", "New Age", None))
        self.comboAlbumGenre.setItemText(79, _translate("DebutForm", "New Wave", None))
        self.comboAlbumGenre.setItemText(80, _translate("DebutForm", "Noise", None))
        self.comboAlbumGenre.setItemText(81, _translate("DebutForm", "Oldies", None))
        self.comboAlbumGenre.setItemText(82, _translate("DebutForm", "Opera", None))
        self.comboAlbumGenre.setItemText(83, _translate("DebutForm", "Other", None))
        self.comboAlbumGenre.setItemText(84, _translate("DebutForm", "Polka", None))
        self.comboAlbumGenre.setItemText(85, _translate("DebutForm", "Pop", None))
        self.comboAlbumGenre.setItemText(86, _translate("DebutForm", "Pop-Folk", None))
        self.comboAlbumGenre.setItemText(87, _translate("DebutForm", "Pop/Funk", None))
        self.comboAlbumGenre.setItemText(88, _translate("DebutForm", "Porn Groove", None))
        self.comboAlbumGenre.setItemText(89, _translate("DebutForm", "Power Ballad", None))
        self.comboAlbumGenre.setItemText(90, _translate("DebutForm", "Pranks", None))
        self.comboAlbumGenre.setItemText(91, _translate("DebutForm", "Primus", None))
        self.comboAlbumGenre.setItemText(92, _translate("DebutForm", "Progressive Rock", None))
        self.comboAlbumGenre.setItemText(93, _translate("DebutForm", "Psychadelic", None))
        self.comboAlbumGenre.setItemText(94, _translate("DebutForm", "Psychadelic Rock", None))
        self.comboAlbumGenre.setItemText(95, _translate("DebutForm", "Punk", None))
        self.comboAlbumGenre.setItemText(96, _translate("DebutForm", "Punk Rock", None))
        self.comboAlbumGenre.setItemText(97, _translate("DebutForm", "R&B", None))
        self.comboAlbumGenre.setItemText(98, _translate("DebutForm", "Rap", None))
        self.comboAlbumGenre.setItemText(99, _translate("DebutForm", "Rave", None))
        self.comboAlbumGenre.setItemText(100, _translate("DebutForm", "Reggae", None))
        self.comboAlbumGenre.setItemText(101, _translate("DebutForm", "Retro", None))
        self.comboAlbumGenre.setItemText(102, _translate("DebutForm", "Revival", None))
        self.comboAlbumGenre.setItemText(103, _translate("DebutForm", "Rhythmic Soul", None))
        self.comboAlbumGenre.setItemText(104, _translate("DebutForm", "Rock", None))
        self.comboAlbumGenre.setItemText(105, _translate("DebutForm", "Rock & Roll", None))
        self.comboAlbumGenre.setItemText(106, _translate("DebutForm", "Samba", None))
        self.comboAlbumGenre.setItemText(107, _translate("DebutForm", "Satire", None))
        self.comboAlbumGenre.setItemText(108, _translate("DebutForm", "Showtunes", None))
        self.comboAlbumGenre.setItemText(109, _translate("DebutForm", "Ska", None))
        self.comboAlbumGenre.setItemText(110, _translate("DebutForm", "Slow Jam", None))
        self.comboAlbumGenre.setItemText(111, _translate("DebutForm", "Slow Rock", None))
        self.comboAlbumGenre.setItemText(112, _translate("DebutForm", "Sonata", None))
        self.comboAlbumGenre.setItemText(113, _translate("DebutForm", "Soul", None))
        self.comboAlbumGenre.setItemText(114, _translate("DebutForm", "Sound Clip", None))
        self.comboAlbumGenre.setItemText(115, _translate("DebutForm", "Soundtrack", None))
        self.comboAlbumGenre.setItemText(116, _translate("DebutForm", "Southern Rock", None))
        self.comboAlbumGenre.setItemText(117, _translate("DebutForm", "Space", None))
        self.comboAlbumGenre.setItemText(118, _translate("DebutForm", "Speech", None))
        self.comboAlbumGenre.setItemText(119, _translate("DebutForm", "Swing", None))
        self.comboAlbumGenre.setItemText(120, _translate("DebutForm", "Symphonic Rock", None))
        self.comboAlbumGenre.setItemText(121, _translate("DebutForm", "Symphony", None))
        self.comboAlbumGenre.setItemText(122, _translate("DebutForm", "Tango", None))
        self.comboAlbumGenre.setItemText(123, _translate("DebutForm", "Techno", None))
        self.comboAlbumGenre.setItemText(124, _translate("DebutForm", "Techno-Industrial", None))
        self.comboAlbumGenre.setItemText(125, _translate("DebutForm", "Terror", None))
        self.comboAlbumGenre.setItemText(126, _translate("DebutForm", "Top 40", None))
        self.comboAlbumGenre.setItemText(127, _translate("DebutForm", "Trailer", None))
        self.comboAlbumGenre.setItemText(128, _translate("DebutForm", "Trance", None))
        self.comboAlbumGenre.setItemText(129, _translate("DebutForm", "Trancecore", None))
        self.comboAlbumGenre.setItemText(130, _translate("DebutForm", "Tribal", None))
        self.comboAlbumGenre.setItemText(131, _translate("DebutForm", "Trip-Hop", None))
        self.comboAlbumGenre.setItemText(132, _translate("DebutForm", "Varies", None))
        self.comboAlbumGenre.setItemText(133, _translate("DebutForm", "Vocal", None))
        self.comboAlbumGenre.setItemText(134, _translate("DebutForm", "World Music", None))
        self.label_3.setText(_translate("DebutForm", "Artist", None))
        self.label_4.setText(_translate("DebutForm", "Album title", None))
        self.label.setText(_translate("DebutForm", "Date", None))
        self.label_2.setText(_translate("DebutForm", "Genre", None))
        self.label_5.setText(_translate("DebutForm", "Folder", None))
        self.textAlbumFolder.setText(_translate("DebutForm", "Browse ... ", None))
        self.checkVA.setText(_translate("DebutForm", "Various artists", None))
        self.checkDeleteOtherTags.setText(_translate("DebutForm", "&Delete all other tags", None))
        self.buttonAlbumDir.setText(_translate("DebutForm", "...", None))
        self.label_8.setText(_translate("DebutForm", "Comment", None))
        self.label_9.setText(_translate("DebutForm", "Group", None))
        self.checkAlbumGroupAppend.setText(_translate("DebutForm", "&Append to file names", None))
        self.buttonAlbumReset.setText(_translate("DebutForm", "&Reset", None))
        self.buttonAlbumApply.setText(_translate("DebutForm", "&Apply", None))
        self.checkAlbumTranslit.setText(_translate("DebutForm", "Enable &transliteration", None))
        self.comboAlbumTranslit.setItemText(0, _translate("DebutForm", "Japanese 日本語", None))
        self.comboAlbumTranslit.setItemText(1, _translate("DebutForm", "Korean 한국어", None))
        self.comboAlbumTranslit.setItemText(2, _translate("DebutForm", "Chinese (simplified) 简化字", None))
        self.comboAlbumTranslit.setItemText(3, _translate("DebutForm", "Chinese (traditional) 繁體字", None))
        self.comboAlbumTranslit.setItemText(4, _translate("DebutForm", "Arabic ‎العربية", None))
        self.comboAlbumTranslit.setItemText(5, _translate("DebutForm", "Russian Русский", None))
        self.comboAlbumTranslit.setItemText(6, _translate("DebutForm", "Greek ελληνικά", None))
        self.comboAlbumTranslit.setItemText(7, _translate("DebutForm", "Hebrew עִבְרִית", None))
        self.buttonPrefs.setText(_translate("DebutForm", "P&references...", None))
        self.checkPromptReset.setText(_translate("DebutForm", "P&rompt on reset", None))

