######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 9 16:54:53 2008
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += . /usr/include

# Input
HEADERS += debutform.h prefsdialog.h
FORMS += debutform.ui prefsdialog.ui
SOURCES += debutform.cpp main.cpp prefsdialog.cpp
